source "https://rubygems.org"

gemspec

# Exclude development-only gems from dependabot.
unless ENV["DEPENDABOT"]
  gem "rake"
  gem "rspec", "~> 3.11"

  # Exclude development-only gems from the gemfiles generated by appraisal.
  unless defined?(::Appraisal::Gemfile) && is_a?(::Appraisal::Gemfile)
    gem "appraisal", require: false
    gem "standard", require: false
    gem "simplecov", require: false
    gem "yard", require: false
  end
end
