name: Continuous Integration
on:
  push:
    branches:
      - master
      - actions-*
    tags:
      - v*
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  specs:
    name: Run specs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - ruby: "ruby"
            standardrb: true
            yard: true
          - ruby: "4.0"
          - ruby: "3.0"
          - ruby: "2.7"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Ruby CI
        uses: bdurand/github-actions/ruby-ci@v1.0.1
        with:
          ruby: ${{ matrix.ruby }}
          appraisal: ${{ matrix.appraisal }}
          bundler: ${{ matrix.bundler }}
          standardrb: ${{ matrix.standardrb }}
          yard: ${{ matrix.yard }}
